import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AIApiCaller } from "@/utils/aiApiCaller";

const TestAITools = () => {
  const [output, setOutput] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const testDocumentationGenerator = async () => {
    setIsLoading(true);
    setOutput("Testing...");
    
    try {
      const result = await AIApiCaller.callAIFunction({
        functionName: 'doc-generator',
        body: {
          sourceCode: 'function test() { return "hello"; }',
          docType: 'function',
          docFormat: 'markdown',
          includeOptions: ['examples', 'parameters'],
          userId: null
        },
        fallbackContent: `# Test Documentation

This is a test documentation generated by the fallback system.

## Function: test()

Returns a simple greeting string.

### Example:
\`\`\`javascript
const result = test();
console.log(result); // "hello"
\`\`\`

**Status**: Template generated - Configure GEMINI_API_KEY for AI-powered docs.`,
        handlerType: 'documentation'
      });

      setOutput(result.content);
      console.log('Test result:', result);
    } catch (error) {
      setOutput(`Error: ${error.message}`);
      console.error('Test error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const testCodeGeneration = async () => {
    setIsLoading(true);
    setOutput("Testing...");
    
    try {
      const result = await AIApiCaller.callAIFunction({
        functionName: 'code-generator',
        body: {
          description: 'Create a function that adds two numbers',
          language: 'javascript',
          codeType: 'function',
          complexity: 'simple',
          userId: null
        },
        fallbackContent: `// AI-Generated JavaScript Code
// Description: Create a function that adds two numbers
// Type: function
// Complexity: simple

function addNumbers(a, b) {
  /**
   * Adds two numbers together
   * @param {number} a - First number
   * @param {number} b - Second number
   * @returns {number} Sum of a and b
   */
  return a + b;
}

// Example usage:
const result = addNumbers(5, 3);
console.log(result); // 8

// Configure GEMINI_API_KEY in Supabase for full AI functionality.`,
        handlerType: 'code-generation'
      });

      setOutput(result.content);
      console.log('Test result:', result);
    } catch (error) {
      setOutput(`Error: ${error.message}`);
      console.error('Test error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="w-full max-w-4xl mx-auto">
      <CardHeader>
        <CardTitle>🧪 AI Tools Test Component</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex gap-2">
          <Button onClick={testDocumentationGenerator} disabled={isLoading}>
            Test Documentation Generator
          </Button>
          <Button onClick={testCodeGeneration} disabled={isLoading}>
            Test Code Generation
          </Button>
        </div>
        
        <div>
          <h3 className="font-semibold mb-2">Output:</h3>
          <Textarea
            value={output}
            readOnly
            className="min-h-[300px] font-mono text-sm"
            placeholder="Click a test button to see output..."
          />
        </div>
      </CardContent>
    </Card>
  );
};

export default TestAITools;
